[package]
name = "nexcpp"
version = "1.0.0"
description = "NexCPP — Professional C++ Online Compiler"
authors = ["NexCPP Team"]
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = "2.0.0-rc"

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
